# Generated by Django 4.1.7 on 2023-03-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_productcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='index.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
