# Generated by Django 4.1.7 on 2023-04-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_product_picture_alter_productcart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_products",
                to="base.category",
            ),
        ),
    ]
