# Generated by Django 4.1.7 on 2023-04-13 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
    ]
